{% set name = "aghast" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/scikit-hep/{{ name }}/archive/{{ version }}.tar.gz
  sha256: c6aa20fc37496788295e2515814d1c00ccd171e22712744b393adf5fa9be1d30

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install ./python --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - python-flatbuffers >=1.8.0
    - numpy

test:
  source_files:
    - python/tests
  requires:
    - pytest
  imports:
    - aghast
  commands:
    - py.test python/tests

about:
  home: https://github.com/diana-hep/aghast
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Aggregated, histogram-like statistics, shareable as Flatbuffers.'
  description: |
    Aghast is a histogramming library that does not fill histograms and does not plot them.
    Its role is behind the scenes, to provide better communication between histogramming libraries.
  doc_url: https://mybinder.org/v2/gh/diana-hep/aghast/master?urlpath=lab/tree/binder%2Fexamples.ipynb
  dev_url: https://github.com/diana-hep/aghast

extra:
  recipe-maintainers:
    - chrisburr
    - jpivarski
