travis:
  secure:
    BINSTAR_TOKEN: Szav6X0zNO2hqrMoqwxCmS2zWwNRERt3AluApEi9Nqyzr4XNT6cfn2K2thrYb8GR0gvJY9tSbUgOk/6sZjPKpzvs+ov/ywFu7+68Yf+W/Zh6YvlK6pT+P6HNWqEoNeJJrKN5D/eDnIQ9tNoP8OMfWpqMVdkAnqd+Mp66kZDceGVtTV7eNJZt19iGkmBKBctPteGud+utiukB5mDMweDYkG17aDyhp9qlYYU0rUAOFnrDzD4aCbKnMS9dzs2N0kcyrMn/QAzidGOouxjufS+k/GbtAj8NZYDgWxFMZRVZa/YtP4sCG7PS3XGBNvKGT8c/00iul0jPxUfMMJtPxOzi8T3/TETCH0GKzGffukFTnRyXuM/+r3jICqCVUaW0TNU5HzDALVMIWI8GWMeoO21RR+LPUR0mE+sr4DCErBalYpQcri8lZrUqsc3pNnjm3w9NFjD3IbT56FtU9Ew6tNiY0Y+knJQ7pepI4qApKBnUoqX4uhBxIx4yfDg9KTd7zPn/zVWM+RUW5f46ciXjkAFvKsWutmOrhaE0++JLlseLns0hKb+RUphd+0kpzkyavv7NKLKK+22C0PqIDci0qwqF5F9kUtnousTehTxS05diYUznf9FkXLs/ZF12D+MaESJ/QeZd7Rww3fSChtJ+Kia5+hVAhu1Vz1kSSQC6Ssj0JUU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
